// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uyfnjohydenzdelykjla.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5Zm5qb2h5ZGVuemRlbHlramxhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMjI3ODQsImV4cCI6MjA3MTc5ODc4NH0.iAIsucD8gV49qrKGCvIotACzpqi7xgWzrrpj0UwYNFs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});